apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      sonobuoy.hept.io/status: '{"plugins":[{"plugin":"e2e","node":"","status":"complete"},{"plugin":"systemd_logs","node":"airship","status":"complete"}],"status":"complete"}'
    creationTimestamp: 2018-07-03T05:59:09Z
    labels:
      component: sonobuoy
      run: sonobuoy-master
      tier: analysis
    name: sonobuoy
    namespace: heptio-sonobuoy
    resourceVersion: "186735"
    selfLink: /api/v1/namespaces/heptio-sonobuoy/pods/sonobuoy
    uid: 33c32fc8-7e86-11e8-afec-0800272e6982
  spec:
    containers:
    - command:
      - /bin/bash
      - -c
      - /sonobuoy master --no-exit=true -v 3 --logtostderr
      env:
      - name: SONOBUOY_ADVERTISE_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      image: gcr.io/heptio-images/sonobuoy:v0.11.3
      imagePullPolicy: Always
      name: kube-sonobuoy
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/sonobuoy
        name: sonobuoy-config-volume
      - mountPath: /plugins.d
        name: sonobuoy-plugins-volume
      - mountPath: /tmp/sonobuoy
        name: output-volume
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: sonobuoy-serviceaccount-token-wrw4f
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: airship
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: sonobuoy-serviceaccount
    serviceAccountName: sonobuoy-serviceaccount
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: sonobuoy-config-cm
      name: sonobuoy-config-volume
    - configMap:
        defaultMode: 420
        name: sonobuoy-plugins-cm
      name: sonobuoy-plugins-volume
    - emptyDir: {}
      name: output-volume
    - name: sonobuoy-serviceaccount-token-wrw4f
      secret:
        defaultMode: 420
        secretName: sonobuoy-serviceaccount-token-wrw4f
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-07-03T05:59:09Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-07-06T03:37:19Z
      message: 'containers with unready status: [kube-sonobuoy]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      message: 'containers with unready status: [kube-sonobuoy]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: 2018-07-03T05:59:09Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://030ed12949e59fde51dd29c444a6f30144da4d4b0fc2ba1641c293a6c25dc9e2
      image: gcr.io/heptio-images/sonobuoy:latest
      imageID: docker-pullable://gcr.io/heptio-images/sonobuoy@sha256:d258d5bbb788eb94770b03f615be3c5729b9c28e2532934612f02cd58597fa16
      lastState: {}
      name: kube-sonobuoy
      ready: false
      restartCount: 0
      state:
        terminated:
          containerID: docker://030ed12949e59fde51dd29c444a6f30144da4d4b0fc2ba1641c293a6c25dc9e2
          exitCode: 255
          finishedAt: 2018-07-06T03:36:30Z
          reason: Error
          startedAt: 2018-07-03T06:00:23Z
    hostIP: 192.168.122.7
    phase: Failed
    qosClass: BestEffort
    startTime: 2018-07-03T05:59:09Z
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-07-03T05:59:09Z
    labels:
      component: sonobuoy
      run: sonobuoy-master
    name: sonobuoy-master
    namespace: heptio-sonobuoy
    resourceVersion: "141312"
    selfLink: /api/v1/namespaces/heptio-sonobuoy/services/sonobuoy-master
    uid: 33c4d6e8-7e86-11e8-afec-0800272e6982
  spec:
    clusterIP: 10.99.111.192
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: sonobuoy-master
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
